language: java

jdk:
  - openjdk8
  - openjdk11

services: docker

script:
  - mvn --settings .travis/settings.xml clean verify -B -V

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  # Deployment to maven-central
  - provider: script
    skip_cleanup: true
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-SNAPSHOT)?$"
      jdk: openjdk8

  # Coverage upload:
  - provider: script
    skip_cleanup: true
    script: /bin/bash .travis/codecov_bash.sh
    on:
      jdk: openjdk8
      all_branches: true