@startuml
skinparam ranksep 25
skinparam defaultTextAlignment center
skinparam nodesep 30
skinparam shadowing false
'skinparam linetype ortho

legend right
    |         | Flow |
    |<#red>| Key and Keystore   <b>creation   |
    |<#green>| Viewing and   <b>reading</b>  from KeyStore    |
endlegend

[<&key> Single key template] as KT
together " " as GFT {
   rectangle "Key Set template\n" as KST {
       rectangle "<&key> Key template 1" as k1
       rectangle "<&key> Key template 2" as k2
       k1 -[hidden]down-> k2
   }
   KT -[hidden]down-> KST
}

node "Juggler.generateKeys()" as GK

rectangle "Key Set\n\nSecretKey,\nPrivateKey,\netc.\n" as KS {
    rectangle "<&key> Key 1" as sk1
    rectangle "<&key> Key 2" as sk2
    sk1 -[hidden]-> sk2
 }

rectangle "<&key> Key" as SK

node "Juggler.toKeystore()" as TK

database "\n<b>Java\n<b>KeyStore\n" as JKS

node "Juggler.readKeys()" as RK

rectangle "Key View\n" as KV {
   rectangle "Alias view" as av
   rectangle "Key view" as kv
   av -[hidden]down-> kv
}

node "Query for key" as qsk
node "Add key" as ak
node "Remove key" as rk

KST -[bold,#red]-> GK
KT -[bold,#red]-> GK
GK -[bold,#red]--> KS
GK -[bold,#red]up-> SK
KS -[bold,#red]-> TK
TK -[bold,#red]-> JKS
JKS -[bold,#green]-->> RK
RK -[bold,#green]-->> KV
KV -[bold,#green]up->> KS
KV -[bold,#green]-->> qsk
KV -[bold,#green]-->> ak
KV -[bold,#green]-->> rk

GFT -[hidden]right-> GK
GK -[hidden]down-> KS
KS -[hidden]up-> SK
KS -[hidden]right-> TK

JKS -[hidden]right-> RK
RK -[hidden]right-> KV
KV -[hidden]left-> KS

@enduml