@startuml
skinparam ranksep 20
skinparam nodesep 100


node "Security provider specific (Adapter)" as SPS {
   [java.KeyStore]
   [KeyStorage]
   [Config]
}
node "Generic" as G {
    [KeyGenerator]
    [KeySetTemplate]
    [KeySet]
    [KeySetView]
    [AliasView]
    [KeyView]
}

KeySetTemplate --> KeyGenerator :accepts
note left
  Uses generic interfaces
  that transfer calls to security provider
  so technically is adapter-specific
end note
KeyGenerator --> KeySet :produces
KeySet --> KeyStorage :build
Config -up-> KeyStorage
KeySet --> KeySetView :asView
java.KeyStore -> KeyStorage :load
KeyStorage --> java.KeyStore :save
KeyStorage --> KeySetView :asView
KeySetView --> AliasView
KeySetView --> KeyView
@enduml