name: Develop branch build
on:
  push:
    branches:
      - '**'

jobs:
  Develop-Branch-Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Step 0 - view the secrets/vars names
        shell: bash
        run: |
          echo "$SECRETS_CONTEXT"
          echo "$VARS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARS_CONTEXT: ${{ toJson(vars) }}